{
    "name": "Hito EGP Reports",
    "version": "18.0.0.3",
    "depends": ["l10n_ar_purchase","l10n_ar_purchase_stock","sale_management","l10n_ar_stock"],
    "category": "purchase",
    "summary": "Change the layout of the purchase order and quote report / sales order",
    "data": [
        'views/account_move.xml',
        'views/res_company.xml',
        'views/sale_order.xml',
        'views/purchase_order.xml',
        'report/report_purchase_order.xml',
        'report/report_purchase_quotation.xml',
        'report/report_sale_order.xml',
        'report/report_invoice_document.xml',
        'report/report_delivery_document.xml',
        'report/stock_report_delivery_aggregated_move_lines.xml',
        'report/stock_report_delivery_document.xml',
        'report/report.xml',
        'data/link_invoices_and_pickings.xml',
    ],
    "installable": True,
    "application": False,
}